---
minimum_pre_commit_version: "1.15"
default_stages: [commit]

ci:
  skip: []

repos:
  # ----------------------------------------------
  # Meta hooks
  # ----------------------------------------------

  - repo: meta
    hooks:
      - id: identity
        stages: [manual]
      - id: check-hooks-apply
        stages: [manual]
      - id: check-useless-excludes
        stages: [manual]

  # ####################################################################################
  #
  #       Essential
  #
  # ####################################################################################

  - repo: local
    hooks:
      - id: parse-jsonc-files
        name: Parse jsonc files
        description: Remove // comments from jsonc file and save it as json.
        language: system
        entry: ./remove_jsonc_comments.py
        require_serial: true
        files: '.*\.jsonc'

  # ####################################################################################
  #
  #       FORMATTING
  #
  # ####################################################################################

  # ----------------------------------------------
  # General (code unspecific)
  # ----------------------------------------------

  # code unspecific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539 # frozen: v4.0.1
    hooks:
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]

  # ----------------------------------------------
  # JS / TS / HTML / CSS / MD / JSON / YAML
  # ----------------------------------------------

  # prettier - JS formater
  - repo: https://github.com/pre-commit/mirrors-prettier
    # https://github.com/prettier/prettier
    # Config file: .prettierrc (JSON, YAML)
    # Ignore file: .prettierignore (file ignore pattern)
    rev: a99a3fbe79a9d346cabd02a5e167ad0edafe616b # frozen: v2.3.0
    hooks:
      - id: prettier

  # ####################################################################################
  #
  #       LINTING
  #
  # ####################################################################################

  # ----------------------------------------------
  # General (code unspecific)
  # ----------------------------------------------

  - repo: local
    hooks:
      # Find TODO:|FIXME:|BUG: comments in all files
      # Inline skip: `#i#` directly after the colon after the tag-word
      - id: find-todos
        name: "Find TODO:|FIXME:|BUG: comments"
        description: "Check for TODO:|FIXME:|BUG: comments in all files"
        language: pygrep
        entry: '(^|//!?|#|<!--|;|/\*(\*|!)?|\.\.)\s*(TODO:|FIXME:|BUG:)(?!#i#)'
        exclude: TODO

  # code unspecific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539 # frozen: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
        exclude: '^.*\.rs$'
      - id: detect-private-key

  # ----------------------------------------------
  # JavaScript
  # ----------------------------------------------

  # eslint - JS linter
  - repo: https://github.com/pre-commit/mirrors-eslint
    # https://github.com/eslint/eslint
    # Config file: .eslintrc.json
    # Ignore file: .eslintignore (file ignore pattern)
    rev: 35fae9e419403ae42821f7ff00f360dd109bdd18 # frozen: v7.27.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts, *.tsx
        types: [file]

  # ----------------------------------------------
  # JSON / TOML / YAML
  # ----------------------------------------------

  # JSON specific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539 # frozen: v4.0.1
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml

  # yamllint - yaml linter
  - repo: https://github.com/adrienverge/yamllint
    rev: 85ccd625a382423edd988fcb796c4dd5897886fb # frozen: v1.26.1
    hooks:
      # Config file: .yamllint (yaml) [--config-file]
      # Inline skip: `# yamllint disable-line[ rule:<RULE>]`
      # Block skip: `# yamllint disable[ rule:<RULE>]`
      # Block skip end: `# yamllint enable`
      - id: yamllint
